// src/WebSPA.React.Identity/ClientApp/src/components/ReplyList.tsx
import React, { Component } from 'react';
import { Comment } from '../models/comment';
import { CommentService } from '../services/comment.service';
import './ReplyList.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import Moment from 'moment';
import { ReplyForm } from './ReplyForm';

interface IReplyListProps {
    parent?: Comment,
    replies: Comment[],
    userName: string,
    onDeleteComment: (deletedComment: Comment) => void
}
interface IReplyListState {
}

export class ReplyList extends Component<IReplyListProps, IReplyListState> {
    private commentService = new CommentService();

    constructor(props: IReplyListProps) {
        super(props);
        this.handleEditComment = this.handleEditComment.bind(this);
        this.handleNewComment = this.handleNewComment.bind(this);
    }

    handleEditComment(newComment: Comment, editComment: Comment) {
        editComment.isEditing = false;
        editComment.content = newComment.content;
        editComment.modifiedDate = newComment.modifiedDate;
        this.forceUpdate();
    }

    handleNewComment(newComment: Comment, parentComment?: Comment) {
        if (parentComment) {
            parentComment.isReplying = false;
            parentComment.replies.push(newComment);
            parentComment.numOfReplies = parentComment.replies.length;
            this.forceUpdate();
        }
    }

    delete(reply: Comment) {
        this.commentService.delete(reply.id).then(comment => {
            if (comment) {
                alert("Deleted successfully.");
                this.props.onDeleteComment(reply);
            }
            else {
                alert("Error occurred. Please try again!");
            }
        });
    }

    toggleReplies(reply: Comment) {
        if (!reply.areRepliesLoaded) {
            this.commentService.getReplies(reply.id).then(replies => {
                reply.replies = replies;
                reply.areRepliesLoaded = true;
                reply.isViewing = true;
                console.log("Comment " + reply.id + " loaded, isViewing: " + reply.isViewing);
                this.forceUpdate();
            });
        }
        else {
            reply.isViewing = !reply.isViewing;
            console.log("Comment " + reply.id + " isViewing: " + reply.isViewing);
            this.forceUpdate();
        }
    }

    render() {
        return (
            this.props.replies.map(reply => {
                return (
                    <div className="mb-2 pl-2 reply-list" key={reply.id}>
                        <div>
                            <b>{reply.author.displayName}</b>
                            <span>&nbsp;- {Moment(reply.createdDate).format("HH:mm DD/MMM/YY")}</span>
                            {reply.modifiedDate && <span> (edited)</span>}
                            {reply.isNew && <span><FontAwesomeIcon icon="comment-medical" className="ml-2 text-info"></FontAwesomeIcon></span>}
                        </div>
                        {(reply.author.userName === this.props.userName) && <div>
                            <button className="btn btn-link p-0" onClick={(e: any) => { reply.isEditing = !reply.isEditing; this.forceUpdate(); }}>
                                {!reply.isEditing ? <span>Edit</span> : <span>Close</span >}
                            </button>
                            <span>&nbsp;|&nbsp;</span>
                            <button className="btn btn-link p-0" onClick={(e: any) => { this.delete(reply) }} title="Delete Comment">Delete</button>
                        </div>}
                        {!reply.isEditing ? <div>{reply.content}</div> : <ReplyForm isNew={false} photoId={reply.photoId} editComment={reply} onEditComment={this.handleEditComment} ></ReplyForm>}
                        <div>
                            {(reply.numOfReplies > 0) &&
                                <button className="btn btn-link p-0" onClick={(e: any) => { this.toggleReplies(reply) }}>
                                    {!reply.isViewing ? <span>View</span> : <span>Hide</span>} {reply.numOfReplies} replies
                                </button>}
                            {(reply.numOfReplies > 0) && <span>&nbsp;|&nbsp;</span>}
                            <button className="btn btn-link p-0" onClick={(e: any) => { reply.isReplying = !reply.isReplying; this.forceUpdate(); }}>
                                {!reply.isReplying ? <span>Reply</span> : <span>Close</span>}
                            </button>
                            {reply.isReplying && <ReplyForm isNew={true} photoId={reply.photoId} parentId={reply.id} parentComment={reply} onCreateComment={this.handleNewComment} ></ReplyForm>}
                            {reply.isViewing && <ReplyList parent={reply} replies={reply.replies} userName={this.props.userName} onDeleteComment={this.props.onDeleteComment} ></ReplyList>}
                        </div>
                    </div>
                );
            }));
    }
}

// src/WebSPA.Slim/ClientApp/src/app/components/_partials/reply-list/reply-list.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Comment } from '../../../models/comment';
import { CommentService } from 'src/app/services/comment.service';
import { ToastyService, ToastData } from 'ng2-toasty';

@Component({
  selector: 'app-reply-list',
  templateUrl: './reply-list.component.html',
  styleUrls: ['./reply-list.component.css']
})
export class ReplyListComponent implements OnInit {

  @Input()
  replies: Comment[] = null;
  @Input()
  parent: Comment = null;
  @Input()
  userName: string = null;

  constructor(
    private commentService: CommentService,
    private toasty: ToastyService
  ) { }

  ngOnInit() {
  }

  toggleReplies(reply: Comment) {
    if (!reply.areRepliesLoaded) {
      var result$ = this.commentService.getReplies(reply.id);
      result$.subscribe(
        replies => {
          reply.replies = replies;
          reply.areRepliesLoaded = true;
          reply.isViewing = true;
        },
        err => {
          console.log(err);
        }
      )
    }
    else {
      reply.isViewing = !reply.isViewing;
    }
  }

  delete(reply: Comment) {
    var result$ = this.commentService.delete(reply.id);
    result$.subscribe(
      res => {
        this.toasty.success({
          title: "Success",
          msg: "Deleted successfully.",
          theme: "bootstrap",
          showClose: true,
          timeout: 1500,
        });
        for (var i = 0; i < this.replies.length; i++) {
          if (this.replies[i].id === reply.id) {
            this.replies.splice(i, 1);
            if (this.parent) {
              this.parent.numOfReplies--;
            }
            break;
          }
        }
      },
      err => {
        this.toasty.error({
          title: "Error",
          msg: "Error occurred. Please try again!",
          theme: "bootstrap",
          showClose: true,
          timeout: 1500
        });
        console.log(err);
      }
    );
  }
}
