// src/WebSPA.React.Identity/ClientApp/src/components/EditPhoto.tsx
import React, { Component } from 'react';
import { RouteComponentProps } from 'react-router';
import { GlobalDataContext } from '../context/GlobalDataContext';
import { SaveAlbum } from '../models/album';
import { DisplayMode, MAX_FILE_LENGTH } from '../models/globalData';
import { PositionModel, Photo, PhotoCategory } from '../models/photo';
import { AlbumService } from '../services/album.service';
import { PhotoService } from '../services/photo.service';
import './EditPhoto.css';
import authService from './api-authorization/AuthorizeService';
import GoogleMapReact from 'google-map-react';
import { User } from '../models/user';
import Select from 'react-select';
import { toast } from 'react-toastify';

interface IEditPhotoProps { }
interface IEditPhotoState {
    photo: Photo,
    hasMap: boolean | null,
    albums?: SaveAlbum[]
}

interface IEditPhotoParams {
    id: string;
}

export class EditPhoto extends Component<IEditPhotoProps & RouteComponentProps<IEditPhotoParams>, IEditPhotoState> {
    static contextType = GlobalDataContext;
    context!: React.ContextType<typeof GlobalDataContext>;

    readonly availableCategories: PhotoCategory[] = [
        {
            id: 1,
            name: "aeroplane"
        },
        {
            id: 2,
            name: "bicycle"
        },
        {
            id: 3,
            name: "bird"
        },
        {
            id: 4,
            name: "boat"
        },
        {
            id: 5,
            name: "bottle"
        },
        {
            id: 6,
            name: "bus"
        },
        {
            id: 7,
            name: "car"
        },
        {
            id: 8,
            name: "cat"
        }, {
            id: 9,
            name: "chair"
        },
        {
            id: 10,
            name: "cow"
        },
        {
            id: 11,
            name: "diningtable"
        },
        {
            id: 12,
            name: "dog"
        },
        {
            id: 13,
            name: "horse"
        },
        {
            id: 14,
            name: "motorbike"
        },
        {
            id: 15,
            name: "person"
        },
        {
            id: 16,
            name: "pottedplant"
        },
        {
            id: 17,
            name: "sheep"
        },
        {
            id: 18,
            name: "sofa"
        },
        {
            id: 19,
            name: "train"
        },
        {
            id: 20,
            name: "tvmonitor"
        }
    ];

    private albumService = new AlbumService();
    private photoService = new PhotoService();
    private photoId: number;
    private userName = "";
    private fileInput: React.RefObject<HTMLInputElement>;
    private gmapSearchBoxRef: React.RefObject<HTMLInputElement>;
    private position?: PositionModel | null;

    constructor(props: IEditPhotoProps & RouteComponentProps<IEditPhotoParams>) {
        super(props);
        this.handleSubmit = this.handleSubmit.bind(this);
        this.handleCancel = this.handleCancel.bind(this);
        this.handleNameChange = this.handleNameChange.bind(this);
        this.handleAlbumChange = this.handleAlbumChange.bind(this);
        this.handleTagChange = this.handleTagChange.bind(this);
        this.handleDelete = this.handleDelete.bind(this);
        this.fileInput = React.createRef();
        this.gmapSearchBoxRef = React.createRef();
        this.googleApiLoadedHandler = this.googleApiLoadedHandler.bind(this);
        this.state = {
            photo: {
                id: 0,
                name: "",
                filePath: "",
                boundingBoxFilePath: "",
                width: 0,
                height: 0,
                photoCategories: [],
                locLat: -1,
                locLng: -1,
                centerLat: -1,
                centerLng: -1,
                mapZoom: -1,
                comments: [],
                totalComments: 0,
                createdDate: new Date(),
                modifiedDate: new Date(),
                author: new User(),
                album: new SaveAlbum()
            },
            albums: [],
            hasMap: null
        };
        this.photoId = parseInt(this.props.match.params.id);
    }

    googleApiLoadedHandler(map: google.maps.Map) {
        window.setTimeout(() => {
            if (this.state.hasMap !== null) {
                this.initializeMap(map);
            }
            else {
                this.googleApiLoadedHandler(map);
            }
        }, 200);
    }

    initializeMap(map: google.maps.Map) {
        // Create the search box and link it to the UI element.
        let searchBox = new google.maps.places.SearchBox(this.gmapSearchBoxRef.current as HTMLInputElement);
        searchBox.addListener('places_changed', (e: any) => {
            let places = searchBox.getPlaces();
            if (places && places.length > 0) {
                let bounds = new google.maps.LatLngBounds();
                // For each place, get the icon, name and location.

                places.forEach(function (place) {
                    if (!place.geometry) {
                        console.log("Returned place contains no geometry");
                        return;
                    }

                    if (place.geometry.viewport) {
                        // Only geocodes have viewport.
                        bounds.union(place.geometry.viewport);
                    } else {
                        bounds.extend(place.geometry.location as google.maps.LatLng);
                    }
                });

                map.fitBounds(bounds);
                placeMarkerAndPanTo(map.getCenter() as google.maps.LatLng);
            }
        });
        let marker: google.maps.Marker;
        let placeMarkerAndPanTo = (latLng: google.maps.LatLng) => {
            if (marker)
                marker.setMap(null);
            marker = new google.maps.Marker({
                position: latLng,
                map: map
            });
            map.panTo(latLng);
            let center = map.getCenter() as google.maps.LatLng;
            this.position = {
                latitude: latLng.lat(),
                longitude: latLng.lng(),
                centerLat: center.lat(),
                centerLng: center.lng(),
                mapZoom: map.getZoom()
            };

            marker.addListener('click', (e: any) => {
                marker.setMap(null);
                this.position = null;
            });
        };

        if (this.state.hasMap) {
            placeMarkerAndPanTo(new google.maps.LatLng(this.state.photo.locLat as number, this.state.photo.locLng as number));
        }

        google.maps.event.addListener(map, 'click', (e: any) => {
            placeMarkerAndPanTo(e.latLng);
        });
        google.maps.event.addListener(map, 'bounds_changed', (e: any) => {
            let bound = map.getBounds() as google.maps.LatLngBounds;
            searchBox.setBounds(bound);
            let center = map.getCenter() as google.maps.LatLng;
            this.position = {
                ...this.position,
                centerLat: center.lat(),
                centerLng: center.lng(),
                mapZoom: map.getZoom()
            };
        });
    }

    handleNameChange(event: React.FormEvent<HTMLInputElement>) {
        let currentValue = event.currentTarget.value;
        this.setState((prevState, props) => ({
            photo: {
                ...prevState.photo,
                name: currentValue
            }
        }));
    }

    handleAlbumChange(event: React.FormEvent<HTMLSelectElement>) {
        if (event.currentTarget.value !== "") {
            let currentValue = event.currentTarget.value;
            this.setState((prevState, props) => ({
                photo: {
                    ...prevState.photo,
                    album: {
                        id: parseInt(currentValue) ?? null
                    }
                }
            }));
        }
        else {
            this.setState((prevState, props) => ({
                photo: {
                    ...prevState.photo,
                    album: {}
                }
            }));
        }
    }

    handleTagChange(newValues: any, actionMeta: any) {
        let photoCategories: PhotoCategory[] = newValues as PhotoCategory[];
        this.setState((prevState, props) => ({
            photo: {
                ...prevState.photo,
                photoCategories: photoCategories
            }
        }));
    }

    handleSubmit(event: React.FormEvent<HTMLFormElement>) {
        event.preventDefault();

        if (this.state.photo.name === "") {
            toast("Photo Name required.");
            return;
        }

        let nativeElement = this.fileInput.current;
        let photoFile = null;
        if (nativeElement && nativeElement.files && nativeElement.files.length > 0)
        {
            if (nativeElement.files[0].size > MAX_FILE_LENGTH) {
                toast("File size must not exceed " + MAX_FILE_LENGTH/(1024*1024) + "MB.");
                return;
            }
            else
                photoFile = nativeElement.files[0];
        }

        let photo = this.state.photo;
        if (this.position) {
            photo.locLat = this.position.latitude as number;
            photo.locLng = this.position.longitude as number;
            photo.centerLat = this.position.centerLat as number;
            photo.centerLng = this.position.centerLng as number;
            photo.mapZoom = this.position.mapZoom as number;
        }
        else {
            photo.locLat = null;
            photo.locLng = null;
            photo.centerLat = null;
            photo.centerLng = null;
            photo.mapZoom = null;
        }

        this.photoService.save(photo, photoFile).then(photo => {
            if (photo) {
                toast("Saved successfully.");
                this.props.history.push('/');
            }
            else {
                toast("Error occurred. Please try again!");
            }
        });
    }

    handleCancel(event: React.MouseEvent<HTMLButtonElement>) {
        this.props.history.push('/');
    }

    handleDelete(event: React.MouseEvent<HTMLButtonElement>) {
        this.photoService.delete(this.state.photo?.id as number).then(res => {
            if (res) {
                toast("Deleted successfully.");
                this.props.history.push('/');
            }
            else {
                toast("Error occurred. Please try again!");
            }
        });
    }

    componentDidMount() {
        this.context?.setDisplayMode(DisplayMode.Photo);
        this.context?.setEnableDisplayMode(true);
        this.populateState();
    }

    async populateState() {
        let user = await authService.getUser();
        this.userName = user ? user["http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"] : null;
        let albumQuery = {
            categoryId: null,
            hasLocation: null,
            authorUserName: this.userName
        };
        this.albumService.getAll(albumQuery).then(albums => {
            this.setState({
                albums: albums as SaveAlbum[]
            });
        });
        this.photoService.get(this.photoId).then(photo => {
            if (photo) {
                this.setState({
                    photo: photo,
                    hasMap: (photo.locLat != null) && (photo.locLng != null)
                });
            }
            else {
                this.props.history.push('/');
            }
        });
    }

    render() {
        return (
            <div>
                <h1>Edit Photo</h1>
                <form onSubmit={this.handleSubmit}>
                    <div className="form-group">
                        <h5>Name:</h5>
                        <input id="photoName" name="photoName" type="text" className="form-control col-lg-8"
                            value={this.state.photo.name} onChange={this.handleNameChange} />
                    </div>
                    <div className="form-group">
                        <h5>Photo:</h5>
                        <div className="row mb-2">
                            <div className="col-lg-6 photo-container">
                                <img alt={this.state.photo.name} src={this.state.photo.filePath} className="img-thumbnail" />
                            </div>
                        </div>
                        <div className="row mb-2">
                            <div className="col-12">
                                <input type="file" className="form-control-file" id="photoFile" name="photoFile" ref={this.fileInput} />
                                <i>(File size must not exceed 1MB)</i>
                            </div>
                            <div className="col-lg-2 col-form-label-sm">Please choose photos having these objects:</div>
                            <div className="col-lg-6 text-justify col-form-label-sm">
                                <i>aeroplane, bicycle, bird, boat, bottle, bus, car, cat, chair, cow, diningtable, dog, horse, motorbike,
                                    person, pottedplant, sheep, sofa, train, tvmonitor</i>
                            </div>
                        </div>
                        <div className="row mb-2">
                            <h5 className="col-lg-2">Album:</h5>
                            <div className="col-lg-6">
                                <select className="form-control" id="photoAlbum" name="photoAlbum" value={this.state.photo.album?.id || ""} onChange={this.handleAlbumChange}>
                                    <option value=""></option>
                                    {this.state?.albums?.map(album =>
                                        <option value={album.id} key={album.id}>{album.name}</option>
                                    )}
                                </select>
                            </div>
                        </div>
                        <div className="row">
                            <h5 className="col-lg-2">Tags:</h5>
                            <div className="col-lg-6">
                                <Select id="photoTag" name="photoTag"
                                    className="basic-multi-select"
                                    classNamePrefix="select"
                                    isMulti
                                    value={this.state.photo.photoCategories}
                                    onChange={this.handleTagChange}
                                    options={this.availableCategories}
                                    getOptionLabel={option => option.name}
                                    getOptionValue={option => option.id.toString()} />
                            </div>
                        </div>    
                    </div>
                    <div className="form-group">
                        <div className="row mb-2">
                            <h5 className="col-lg-2">Location:</h5>
                            <div className="col-lg-6">
                                <input id="gmapSearchBox" className="form-control" type="text"
                                    placeholder="Type location here..." ref={this.gmapSearchBoxRef} />
                            </div>
                        </div>
                        <div className="row">
                            <div className="col-lg-8">
                                <div id="gmap">
                                    <GoogleMapReact
                                        bootstrapURLKeys={{
                                            key: "",
                                            libraries: 'places'
                                        }}
                                        yesIWantToUseGoogleMapApiInternals
                                        onGoogleApiLoaded={({ map }) => this.googleApiLoadedHandler(map)}
                                        defaultCenter={{ lat: 3.140853, lng: 101.693207 }} /* KUL */
                                        defaultZoom={12}
                                        options={{ mapTypeId: 'roadmap' }}
                                    />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-8">
                        <div className="row">
                            <button className="btn btn-secondary mr-3" type="button" onClick={this.handleCancel}>Back</button>
                            <button className="btn btn-primary mr-3" type="submit">Save</button>
                            <button className="btn btn-danger" type="button" onClick={this.handleDelete}>Delete</button>
                        </div>
                    </div>
                </form>
            </div>
        );
    }
}

// src/WebSPA/ClientApp/src/app/components/edit-photo/edit-photo.component.ts
import { GlobalDataService } from 'src/app/services/globalData.service';
import { GlobalData, DisplayMode, MAX_FILE_LENGTH } from 'src/app/models/globalData';
import { AuthorizeService } from './../../../api-authorization/authorize.service';
import { NameClaimType } from './../../../api-authorization/api-authorization.constants';
import { AlbumService } from './../../services/album.service';
import { SaveAlbum, AlbumQuery } from './../../models/album';
import { ActivatedRoute, Router } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import { LocationService } from './../../services/location.service';
import { PhotoService } from './../../services/photo.service';
import { PositionModel, Photo, PhotoCategory } from './../../models/photo';
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { map } from 'rxjs/operators';

@Component({
  selector: 'app-edit-photo',
  templateUrl: './edit-photo.component.html',
  styleUrls: ['./edit-photo.component.css']
})
export class EditPhotoComponent implements OnInit {
  readonly tagSeparator: string = ", ";
  readonly availableCategories: PhotoCategory[] = [
    {
      id: 1,
      name: "aeroplane"
    },
    {
      id: 2,
      name: "bicycle"
    },
    {
      id: 3,
      name: "bird"
    },
    {
      id: 4,
      name: "boat"
    },
    {
      id: 5,
      name: "bottle"
    },
    {
      id: 6,
      name: "bus"
    },
    {
      id: 7,
      name: "car"
    },
    {
      id: 8,
      name: "cat"
    }, {
      id: 9,
      name: "chair"
    },
    {
      id: 10,
      name: "cow"
    },
    {
      id: 11,
      name: "diningtable"
    },
    {
      id: 12,
      name: "dog"
    },
    {
      id: 13,
      name: "horse"
    },
    {
      id: 14,
      name: "motorbike"
    },
    {
      id: 15,
      name: "person"
    },
    {
      id: 16,
      name: "pottedplant"
    },
    {
      id: 17,
      name: "sheep"
    },
    {
      id: 18,
      name: "sofa"
    },
    {
      id: 19,
      name: "train"
    },
    {
      id: 20,
      name: "tvmonitor"
    }
  ];
  photo: Photo = {
    id: 0,
    name: "",
    filePath: "",
    boundingBoxFilePath: "",
    width: 0,
    height: 0,
    photoCategories: [],
    locLat: null,
    locLng: null,
    centerLat: null,
    centerLng: null,
    mapZoom: null,
    comments: [],
    totalComments: 0,
    createdDate: null,
    modifiedDate: null,
    author: null,
    album: null
  };
  photoTags: number[];
  position: PositionModel = null;
  albums: SaveAlbum[];
  selectedAlbums: number[];
  albumQuery: AlbumQuery;
  userName: string;
  globalData: GlobalData = {
    displayMode: DisplayMode.Photo,
    enableDisplayMode: false
  };

  @ViewChild("photoFile", { static: false }) fileInput: ElementRef;
  @ViewChild('gmap', { static: false }) gmapElement: any;
  map: google.maps.Map;
  @ViewChild('gmapSearchBox', { static: false }) gmapSearchBox: any;
  searchBox: google.maps.places.SearchBox;
  marker: google.maps.Marker;
  hasMap: boolean = null;

  constructor(private photoService: PhotoService,
    private locationService: LocationService,
    private toastr: ToastrService,
    private route: ActivatedRoute,
    private router: Router,
    private albumService: AlbumService,
    private authorizeService: AuthorizeService,
    private globalDataService: GlobalDataService) { }

  ngOnInit() {
    this.globalDataService.changeDisplayMode(this.globalData);
    this.route.params.subscribe(p => {
      this.authorizeService.getUser().pipe(map(u => u && u[NameClaimType])).subscribe(userName => {
        this.userName = userName;
        this.photoService.get(+p['id']).subscribe(photo => {
          if (photo) {
            if (photo.author.userName == this.userName) {
              this.photo = photo;  
              this.photoTags = this.photo.photoCategories.map(c => c.id);
              this.hasMap = (photo.locLat != null) && (photo.locLng != null);
              if (this.photo.album)
                this.selectedAlbums = [this.photo.album.id];
              else
                this.selectedAlbums = [];
              this.initializeMap();
              this.loadAlbums();
            }
            else {
              this.router.navigate(['/photo/' + photo.id]);
            }
          }
          else {
            this.router.navigate(['/']);
          }
        },
          err => {
            this.router.navigate(['/']);
          });
      });
    });
  }

  loadAlbums() {
    this.albumQuery = {
      categoryId: null,
      hasLocation: null,
      authorUserName: this.userName
    };
    this.albumService.getAll(this.albumQuery).subscribe(albums => {
      this.albums = albums;
    });
  }

  initializeMap() {
    if (this.gmapElement != undefined) {
      // Create map
      var mapProp = {
        center: new google.maps.LatLng(3.140853, 101.693207), // KUL
        zoom: 12,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      if (this.hasMap) {
        mapProp.center = new google.maps.LatLng(this.photo.centerLat, this.photo.centerLng);
        mapProp.zoom = this.photo.mapZoom;
      }
      this.map = new google.maps.Map(this.gmapElement.nativeElement, mapProp);

      if (this.hasMap) {
        this.position = {
          latitude: this.photo.locLat,
          longitude: this.photo.locLng
        };

        this.placeMarkerAndPanTo(new google.maps.LatLng(this.photo.locLat, this.photo.locLng));
      }
      else {
        // Set map to current location
        this.locationService.getLocation().subscribe(loc => {
          var gPosition = new google.maps.LatLng(loc.coords.latitude, loc.coords.longitude);
          this.map.setCenter(gPosition);
        });
      }

      // Listen to map's click event
      google.maps.event.addListener(this.map, 'click', (e) => {
        this.placeMarkerAndPanTo(e.latLng);
      });

      // Create the search box and link it to the UI element.
      this.searchBox = new google.maps.places.SearchBox(this.gmapSearchBox.nativeElement);

      // Bias the SearchBox results towards current map's viewport.
      google.maps.event.addListener(this.map, 'bounds_changed', (e) => {
        this.searchBox.setBounds(this.map.getBounds());
      });

      // Listen for the event fired when the user selects a prediction and retrieve
      // more details for that place.
      this.searchBox.addListener('places_changed', (e) => {
        var places = this.searchBox.getPlaces();

        if (places.length == 0) {
          return;
        }

        // For each place, get the icon, name and location.
        var bounds = new google.maps.LatLngBounds();
        places.forEach(function (place) {
          if (!place.geometry) {
            console.log("Returned place contains no geometry");
            return;
          }

          if (place.geometry.viewport) {
            // Only geocodes have viewport.
            bounds.union(place.geometry.viewport);
          } else {
            bounds.extend(place.geometry.location);
          }
        });

        this.map.fitBounds(bounds);
        this.placeMarkerAndPanTo(this.map.getCenter());
      });
    }
  }

  placeMarkerAndPanTo(latLng: google.maps.LatLng) {
    this.position = {
      latitude: latLng.lat(),
      longitude: latLng.lng()
    };
    if (this.marker)
      this.marker.setMap(null);
    this.marker = new google.maps.Marker({
      position: latLng,
      map: this.map
    });
    this.map.panTo(latLng);

    this.marker.addListener('click', (e) => {
      this.marker.setMap(null);
      this.position = null;
    });
  }

  submit() {
    var nativeElement: HTMLInputElement = this.fileInput.nativeElement;
    var photoFile = null;
    if (nativeElement.files && nativeElement.files.length > 0) {
      photoFile = nativeElement.files[0];
      if (nativeElement.files[0].size > MAX_FILE_LENGTH) {
        this.toastr.error("File size must not exceed 1MB.", "Error", {
          timeOut: 1500,
          closeButton: true
        });
        return;
      }      
    }
    if (this.position) {
      this.photo.locLat = this.position.latitude;
      this.photo.locLng = this.position.longitude;
      this.photo.centerLat = this.map.getCenter().lat();
      this.photo.centerLng = this.map.getCenter().lng();
      this.photo.mapZoom = this.map.getZoom();
    }
    else {
      this.photo.locLat = null;
      this.photo.locLng = null;
      this.photo.centerLat = null;
      this.photo.centerLng = null;
      this.photo.mapZoom = null;
    }
    this.photo.photoCategories = this.availableCategories.filter(cat => {
      return this.photoTags.indexOf(cat.id) >= 0;
    });
    if (this.selectedAlbums) {
      this.photo.album = this.albums.filter(album => {
        return this.selectedAlbums.indexOf(album.id) >= 0;
      })[0];
    }

    var result$ = this.photoService.save(this.photo, photoFile);
    result$.subscribe(
      photo => {
        if (photo) {
          this.toastr.success("Saved successfully.", "Success", {
            timeOut: 1500,
            closeButton: true
          });
          this.photo = photo;
          this.fileInput.nativeElement.value = "";
        }
        else {
          this.toastr.error("Error occurred. Please try again!", "Error", {
            timeOut: 1500,
            closeButton: true
          });
        }
      },
      err => {
        this.toastr.error("Error occurred. Please try again!", "Error", {
          timeOut: 1500,
          closeButton: true
        });
        console.log(err);
      }
    );
  }

  back() {
    this.router.navigate(['/photo/' + this.photo.id]);
  }

  delete() {
    var result$ = this.photoService.delete(this.photo.id);
    var router = this.router;
    result$.subscribe(
      res => {
        this.toastr.success("Deleted successfully.", "Success", {
          timeOut: 1500,
          closeButton: true
        }).onHidden.subscribe(() => {
          router.navigate(['/']);
        });
      },
      err => {
        this.toastr.error("Error occurred. Please try again!", "Error", {
          timeOut: 1500,
          closeButton: true
        });        
        console.log(err);
      }
    );
  }
}

<h1>Edit Photo</h1>
<form #f="ngForm" (ngSubmit)="submit()">
  <div class="form-group">
    <h5 for="photoName">Name:</h5>
    <input id="photoName" name="photoName" type="text" class="form-control col-lg-8" [(ngModel)]="photo.name" />
  </div>
  <div class="form-group">
    <h5 for="photoFile">Photo:</h5>
    <div class="row mb-2">
      <div class="col-lg-6 photo-container" [class.portrait]="photo.width < photo.height">
        <img src="{{ photo.filePath }}" class="img-thumbnail">
      </div>
    </div>
    <div class="row mb-2">
      <div class="col-12">
        <input type="file" class="form-control-file" id="photoFile" name="photoFile" #photoFile />
        <i>(File size must not exceed 1MB)</i>
      </div>
      <div class="col-lg-2 col-form-label-sm">Please choose photos having these objects:</div>
      <div class="col-lg-6 text-justify col-form-label-sm">
        <i>aeroplane, bicycle, bird, boat, bottle, bus, car, cat, chair, cow, diningtable, dog, horse, motorbike,
          person, pottedplant, sheep, sofa, train, tvmonitor</i>
      </div>
    </div>
    <div class="row mb-2">
      <h5 class="col-lg-2" for="photoAlbum">Album:</h5>
      <div class="col-lg-6">
        <ng-select id="photoAlbum" name="photoAlbum" [items]="albums" bindLabel="name" bindValue="id"
          [hideSelected]="true" multiple="false" maxSelectedItems=1 [(ngModel)]="selectedAlbums">
        </ng-select>
      </div>
    </div>
    <div class="row">
      <h5 class="col-lg-2" for="photoTag">Tags:</h5>
      <div class="col-lg-6">
        <ng-select id="photoTag" name="photoTag" [items]="availableCategories" bindLabel="name" bindValue="id"
          [hideSelected]="true" multiple="true" [(ngModel)]="photoTags">
        </ng-select>
      </div>
    </div>    
  </div>
  <div class="form-group">
    <div class="row mb-2">
      <h5 class="col-lg-2" for="gmapSearchBox">Location:</h5>
      <div class="col-lg-6">
        <input id="gmapSearchBox" class="form-control" type="text" placeholder="Type location here..." #gmapSearchBox
          (keydown.enter)="$event.preventDefault()">
      </div>
    </div>
    <div class="row">
      <div class="col-lg-8">
        <div id="gmap" #gmap></div>
      </div>
    </div>
  </div>
  <div class="col-lg-8">
    <div class="row">
      <button class="btn btn-secondary mr-3" type="button" (click)="back()">Back</button>
      <button class="btn btn-primary mr-3" type="button" (click)="submit()">Save</button>
      <button class="btn btn-danger" type="button" (click)="delete()">Delete</button>
    </div>
  </div>
</form>
