// MyAlbum.WebSPA/ClientApp/src/app/components/explore-album/explore-album.component.ts
import { GlobalDataService } from 'src/app/services/globalData.service';
import { GlobalData, DisplayMode } from 'src/app/models/globalData';
import { Album, AlbumQuery } from './../../models/album';
import { AlbumService } from './../../services/album.service';
import { Component, OnInit, ViewChildren, QueryList } from '@angular/core';

declare var Tessarray: any;

@Component({
  selector: 'app-explore-album',
  templateUrl: './explore-album.component.html',
  styleUrls: ['./explore-album.component.css']
})
export class ExploreAlbumComponent implements OnInit {
  albums: Album[];
  query: AlbumQuery;
  globalData: GlobalData = {
    displayMode: DisplayMode.Album,
    enableDisplayMode: true
  };  
  @ViewChildren('albumBoxes') albumBoxes: QueryList<any>;

  constructor(private albumService: AlbumService,
    private globalDataService: GlobalDataService) { }

  ngOnInit() {
    this.globalDataService.changeDisplayMode(this.globalData);
    this.albumService.getAll(this.query)
      .subscribe(albums => {
        this.albums = albums;
      });
  }

  ngAfterViewInit() {
    this.albumBoxes.changes.subscribe(t => {
      this.ngForRendered();
    });
  }

  ngForRendered() {
    var tessarray = new Tessarray(".album-gallery", ".album-box", {
      selectorClass: false,
      imageClass: ".album-box .main-photo img",
      boxTransition: false,
      boxTransformOutTransition: false,
      flickr: {
        // http://flickr.github.io/justified-layout/
        targetRowHeight: 300,
        targetRowHeightTolerance: 0,
        boxSpacing: {
          horizontal: 20,
          vertical: 20
        },
        containerPadding: 0,
        forceAspectRatio: 1
      }
    });
  }
}

<div class="album-gallery">
  <a #albumBoxes *ngFor="let a of albums" href="/?albumId={{ a.id }}">
    <div class="album-box rounded">
      <div class="main-photo" [class.full]="a.subPhotos[0] == null">
        <img src="{{ a.mainPhoto.filePath }}" alt="{{ a.name }}" *ngIf="a.mainPhoto != null">
        <img class="default-album" src="/default_album.jpg" alt="{{ a.name }}" *ngIf="a.mainPhoto == null">
      </div>
      <div class="sub-photos">
        <div class="photo" *ngFor="let p of a.subPhotos">
          <img src="{{ p.filePath }}" alt="{{ a.name }}" *ngIf="p != null">
        </div>
      </div>
      <div class="content">
        <div class="text">
          <div>
            <div class="title" title="{{ a.name }}">{{ a.name }}</div>
            <div class="author">by {{ a.author.displayName }}</div>          
          </div>
        </div>
        <div class="total-photos">
          <div>
            <i class="fas fa-images"></i> {{a.photos.length}}
          </div>
        </div>
      </div>
    </div>
  </a>
</div>

// src/WebSPA.React.Identity/ClientApp/src/components/ExploreAlbum.tsx
import React, { Component } from 'react';
import { Album } from '../models/album';
import { AlbumService } from '../services/album.service';
import './ExploreAlbum.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { GlobalDataContext } from '../context/GlobalDataContext';
import { DisplayMode } from '../models/globalData';

declare const Tessarray: any;

interface IExploreAlbumProps { }
interface IExlploreAlbumState {
    albums: Album[];
}

export class ExploreAlbum extends Component<IExploreAlbumProps, IExlploreAlbumState> {
    static contextType = GlobalDataContext;
    context!: React.ContextType<typeof GlobalDataContext>;

    private albumService = new AlbumService();

    constructor(props: IExploreAlbumProps) {
        super(props);
        this.state = {
            albums: []
        };
    }

    componentDidMount() {
        this.albumService.getAll([]).then(data => {
            this.setState({
                albums: data
            });
        });
        this.context?.setDisplayMode(DisplayMode.Album);
    }

    render() {
        return (
            <div className="album-gallery">
                {this.state.albums.map(album =>
                    <a href={"/album/" + album.id} key={album.id}>
                        <div className="album-box rounded">
                            <div className={"main-photo" + ((album.subPhotos[0] == null) ? " full" : "")}>
                                {(album.mainPhoto != null) && <img src={album.mainPhoto.filePath} alt={album.name ?? ""} />}
                                {(album.mainPhoto == null) && <img className="default-album" src="/default_album.jpg" alt={album.name ?? ""} />}
                            </div>
                            <div className="sub-photos">
                                {album.subPhotos.map(photo =>
                                    (photo != null) &&
                                    <div className="photo" key={photo.id}>
                                        <img src={photo.filePath} alt={album.name ?? ""} />
                                    </div>
                                )}
                            </div>
                            <div className="content">
                                <div className="text">
                                    <div>
                                        <div className="title" title={album.name ?? ""}>{album.name}</div>
                                        <div className="author">by {album.author?.displayName}</div>
                                    </div>
                                </div>
                                <div className="total-photos">
                                    <div>
                                        <FontAwesomeIcon icon="images" /> {album.photos.length}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                )}
            </div>
        );
    }

    componentDidUpdate(prevProps: IExploreAlbumProps, prevState: IExlploreAlbumState) {
        const tessarray = new Tessarray(".album-gallery", ".album-box", {
            selectorClass: false,
            imageClass: ".album-box .main-photo img",
            boxTransition: false,
            boxTransformOutTransition: false,
            flickr: {
                // http://flickr.github.io/justified-layout/
                targetRowHeight: 300,
                targetRowHeightTolerance: 0.25,
                boxSpacing: {
                    horizontal: 20,
                    vertical: 20
                },
                containerPadding: {
                    left: 0,
                    right: 15,
                    bottom: 0,
                    top: 0
                },
                forceAspectRatio: 1
            }
        });
    }
}
