// MyAlbum.WebSPA/ClientApp/src/app/components/home/home.component.ts
import { Photo } from './../../models/photo';
import { PhotoService } from './../../services/photo.service';
import { Component, OnInit, QueryList, ViewChildren } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

declare var Tessarray: any;

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  photos: Photo[];
  query: any = {};
  @ViewChildren('imageBoxes') imageBoxes: QueryList<any>;

  constructor(
    private photoService: PhotoService,
    private route: ActivatedRoute
  ) {
    route.queryParams.subscribe(p => {
      if (+p['catId'])
        this.query.categoryId = +p['catId'];
      else
        delete this.query.categoryId;
      this.photoService.getAll(this.query)
        .subscribe(photos => {
          this.photos = photos;
        });
    });
  }

  ngOnInit() {
  }

  ngAfterViewInit() {
    this.imageBoxes.changes.subscribe(t => {
      this.ngForRendered();
    });
  }

  ngForRendered() {
    var tessarray = new Tessarray(".explore-gallery", ".image-box", {
      selectorClass: false,
      boxTransition: false,
      boxTransformOutTransition: false,
      flickr: {
        // http://flickr.github.io/justified-layout/
        targetRowHeight: 300,
        targetRowHeightTolerance: 0.05,
        boxSpacing: {
          horizontal: 20,
          vertical: 20
        },
        containerPadding: 0
      }
    });
  }
}

<div class="row" *ngIf="globalData.displayMode == 'album'">
  <div class="col-lg-6">
    <h3>
      {{ album.name }}
      <span *ngIf="isEditable()">
        &nbsp;
        <a class="btn btn-secondary float-right" href="/album/edit/{{ album.id }}">Edit</a>
      </span>
    </h3>
    <hr />
  </div>
</div>
<div class="explore-gallery">
  <a #imageBoxes *ngFor="let p of photos" href="/photo/{{ p.id }}">
    <div class="image-box rounded">
      <img src="{{ p.filePath }}" alt="{{ p.name }}">
      <div class="interaction-view">
        <div class="interaction-bar">
          <div class="text">
            <div class="title" title="{{ p.name }}">{{ p.name }}</div>
            <div class="author" title="{{ p.author.displayName }}">by {{ p.author.displayName }}</div>
          </div>
          <div class="engagement">
            <div class="total-comments" title="{{ p.totalComments }}">
                <i class="fas fa-comments"></i> {{ p.totalComments }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </a>
</div>

// src/WebSPA.React.Identity/ClientApp/src/components/Home.tsx
import React, { Component } from 'react';
import { Photo } from '../models/photo';
import { PhotoService } from '../services/photo.service';
import './Home.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

declare var Tessarray: any;

interface IHomeProps { }
interface IHomeState {
    photos: Photo[];
}

export class Home extends Component<IHomeProps, IHomeState> {
    private photoService = new PhotoService();

    constructor(props: IHomeProps) {
        super(props);
        this.state = {
            photos: []
        };
    }

    componentDidMount() {
        this.photoService.getAll([]).then(data => {
            this.setState({
                photos: data
            });
        });
    }

    render() {
        return (
            <div className="explore-gallery">
                {this.state.photos.map(photo =>
                    <a href={"/photo/" + photo.id} key={photo.id}>
                        <div className="image-box rounded">
                            <img src={photo.filePath} alt={photo.name} />
                            <div className="interaction-view">
                                <div className="interaction-bar">
                                    <div className="text">
                                        <div className="title" title={photo.name}>{photo.name}</div>
                                        <div className="author" title={photo.author.displayName}>by {photo.author.displayName}</div>
                                    </div>
                                    <div className="engagement">
                                        <div className="total-comments" title={photo.totalComments.toString()}>
                                            <FontAwesomeIcon icon="comments" /> {photo.totalComments}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                )}
            </div>
        );
    }

    componentDidUpdate(prevProps: IHomeProps, prevState: IHomeState) {
        var tessarray = new Tessarray(".explore-gallery", ".image-box", {
            selectorClass: false,
            boxTransition: false,
            boxTransformOutTransition: false,
            flickr: {
                // http://flickr.github.io/justified-layout/
                targetRowHeight: 300,
                targetRowHeightTolerance: 0.25,
                boxSpacing: {
                    horizontal: 20,
                    vertical: 20
                },
                containerPadding: 0
            }
        });
    }
}
