// MyAlbum.WebSPA/ClientApp/src/app/components/_partials/reply-list/reply-list.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Comment } from '../../../models/comment';
import { CommentService } from 'src/app/services/comment.service';

@Component({
  selector: 'app-reply-list',
  templateUrl: './reply-list.component.html',
  styleUrls: ['./reply-list.component.css']
})
export class ReplyListComponent implements OnInit {

  @Input()
  replies: Comment[] = null;

  constructor(
    private commentService: CommentService
  ) { }

  ngOnInit() {
  }

  toggleReplies(reply: Comment) {
    if (!reply.areRepliesLoaded) {
      var result$ = this.commentService.getReplies(reply.id);
      result$.subscribe(
        replies => {
          reply.replies = replies;
          reply.areRepliesLoaded = true;
          reply.isViewing = true;
        },
        err => {
          console.log(err);
        }
      )
    }
    else {
      reply.isViewing = !reply.isViewing;
    }
  }
}
<div *ngFor="let reply of replies" class="mb-2 pl-2 reply-list">
  <div>
    <b>{{reply.author.displayName}}</b>
    <span>&nbsp;- {{reply.createdDate | date : "HH:mm dd/MMM/yy"}}</span>
    <span *ngIf="reply.isNew"><i class="fas fa-comment-medical ml-2 text-info"></i></span>
  </div>
  <div>{{reply.content}}</div>
  <div>
    <a [routerLink]="" (click)="toggleReplies(reply)" *ngIf="reply.numOfReplies > 0">
      <span *ngIf="!reply.isViewing">View</span>
      <span *ngIf="reply.isViewing">Hide</span>
      {{reply.numOfReplies}} replies</a>
    <span *ngIf="reply.numOfReplies > 0">&nbsp;|&nbsp;</span>
    <a [routerLink]="" (click)="reply.isReplying = !reply.isReplying">
      <span *ngIf="!reply.isReplying">Reply</span>
      <span *ngIf="reply.isReplying">Close</span>
    </a>
    <app-reply-form *ngIf="reply.isReplying" [parent]="reply"></app-reply-form>
    <app-reply-list *ngIf="reply.isViewing" [replies]="reply.replies"></app-reply-list>
  </div>
</div>

// src/WebSPA.React.Identity/ClientApp/src/components/ReplyList.tsx
import React, { Component } from 'react';
import { Comment } from '../models/comment';
import { CommentService } from '../services/comment.service';
import './ReplyList.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import Moment from 'moment';

interface IReplyListProps {
    parent?: Comment,
    replies: Comment[],
    userName: string
}
interface IReplyListState {
}

export class ReplyList extends Component<IReplyListProps, IReplyListState> {
    private commentService = new CommentService();

    delete(reply: Comment) {

    }

    toggleReplies(reply: Comment) {
        if (!reply.areRepliesLoaded) {
            this.commentService.getReplies(reply.id).then(replies => {
                reply.replies = replies;
                reply.areRepliesLoaded = true;
                reply.isViewing = true;
                console.log("Comment " + reply.id + " loaded, isViewing: " + reply.isViewing);
                this.forceUpdate();
            });
        }
        else {
            reply.isViewing = !reply.isViewing;
            console.log("Comment " + reply.id + " isViewing: " + reply.isViewing);
            this.forceUpdate();
        }
    }

    render() {
        return (
            this.props.replies.map(reply => {
                return (
                    <div className="mb-2 pl-2 reply-list" key={reply.id}>
                        <div>
                            <b>{reply.author.displayName}</b>
                            <span>&nbsp;- {Moment(reply.createdDate).format("HH:mm DD/MMM/YY")}</span>
                            {reply.modifiedDate && <span> (edited)</span>}
                            {reply.isNew && <span><FontAwesomeIcon icon="comment-medical" className="ml-2 text-info"></FontAwesomeIcon></span>}
                        </div>
                        {(reply.author.userName === this.props.userName) && <div>
                            <button className="btn btn-link" onClick={(e: any) => { reply.isEditing = !reply.isEditing }}>
                                {!reply.isEditing ? <span>Edit</span> : <span>Close</span >}
                            </button>
                            <span>&nbsp;|&nbsp;</span>
                            <button className="btn btn-link" onClick={(e: any) => { this.delete(reply) }} title="Delete Comment">Delete</button>
                        </div>}
                        {!reply.isEditing ? <div>{reply.content}</div> : ""/*<app-edit-reply *ngIf="reply.isEditing" [comment]="reply"></app-edit-reply>*/}
                        <div>
                            {(reply.numOfReplies > 0) &&
                                <button className="btn btn-link" onClick={(e: any) => { this.toggleReplies(reply) }}>
                                    {!reply.isViewing ? <span>View</span> : <span>Hide</span>} {reply.numOfReplies} replies
                                </button>}
                            {(reply.numOfReplies > 0) && <span>&nbsp;|&nbsp;</span>}
                            <button className="btn btn-link" onClick={(e: any) => { reply.isReplying = !reply.isReplying }}>
                                {!reply.isReplying ? <span>Reply</span> : <span>Close</span>}
                            </button>
                            {/*<app-reply-form *ngIf="reply.isReplying" [parent]="reply"></app-reply-form>*/}
                            {reply.isViewing && <ReplyList parent={reply} replies={reply.replies} userName={this.props.userName}></ReplyList>}
                        </div>
                    </div>
                );
            }));
    }
}
