// src/WebSPA.Identity/ClientApp/src/app/components/view-photo/view-photo.component.ts
import { NameClaimType } from './../../../api-authorization/api-authorization.constants';
import { AuthorizeService } from './../../../api-authorization/authorize.service';
import { GlobalDataService } from 'src/app/services/globalData.service';
import { GlobalData, DisplayMode } from 'src/app/models/globalData';
import { Photo } from './../../models/photo';
import { PhotoService } from './../../services/photo.service';
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Comment, findReplyInComment, mergeNewComment } from './../../models/comment';
import { CommentService } from 'src/app/services/comment.service';
import { ToastyService } from 'ng2-toasty';
import { CommentAdded } from 'src/app/models/commentAdded';
import { map } from 'rxjs/operators';

@Component({
  selector: 'app-view-photo',
  templateUrl: './view-photo.component.html',
  styleUrls: ['./view-photo.component.css'],
  host: {
    '(window:resize)': 'onResize($event)'
  }
})
export class ViewPhotoComponent implements OnInit {
  photo: Photo = {
    id: 0,
    name: "",
    filePath: "",
    boundingBoxFilePath: "",
    width: 0,
    height: 0,
    photoCategories: [],
    locLat: null,
    locLng: null,
    centerLat: null,
    centerLng: null,
    mapZoom: null,
    comments: [],
    totalComments: 0,
    createdDate: null,
    modifiedDate: null,
    author: null,
    album: null
  };
  newComment: Comment = {
    id: 0,
    photoId: 0,
    parentId: null,
    content: "",
    author: {
      userName: "",
      firstName: "",
      lastName: "",
      displayName: "",
      createdDate: null,
      modifiedDate: null
    },
    connectionId: "",
    isNew: true,
    isReplying: false,
    isViewing: false,
    isEditing: false,
    areRepliesLoaded: false,
    numOfReplies: 0,
    replies: [],
    createdDate: null,
    modifiedDate: null
  };
  photoId: number = 0;
  isShownBoundingBox: boolean = false;
  hasMap: boolean = null;
  globalData: GlobalData = {
    displayMode: DisplayMode.Photo,
    enableDisplayMode: false
  };
  userName: string;
  maxWidth: number = 0;
  maxHeight: number = 0;
  flipContainerWidth: number = 0;
  gmapHeight: number = 0;

  @ViewChild('gmap', { static: false }) gmapElement: any;
  map: google.maps.Map;

  @ViewChild('photoContainer', { static: false }) photoContainer: ElementRef;
  @ViewChild('imagePhoto', { static: false }) imageElement: ElementRef;

  constructor(
    private photoService: PhotoService,
    private commentService: CommentService,
    private route: ActivatedRoute,
    private router: Router,
    private toasty: ToastyService,
    private globalDataService: GlobalDataService,
    private authorizeService: AuthorizeService
  ) { }

  onResize(event) {
    this.calcPhotoSize();
  }

  ngOnInit() {
    this.globalDataService.changeDisplayMode(this.globalData);
    this.authorizeService.getUser().pipe(map(u => u && u[NameClaimType])).subscribe(userName => {
      this.userName = userName;
    });
    this.route.params.subscribe(p => {
      this.photoId = +p['id'];
      this.newComment.photoId = this.photoId;
      this.photoService.get(this.photoId).subscribe(
        observable$ => {
          observable$.subscribe(
            photo => {
              if (photo) {
                this.photo = photo;
                this.hasMap = (photo.locLat != null) && (photo.locLng != null);
                this.initializeMap();
                this.calcPhotoSize();
              }
              else {
                this.router.navigate(['/']);
              }
            });
        },
        err => {
          this.router.navigate(['/']);
        });
    });

    this.commentService.addedComment$.subscribe(newComment => this.addedCommentSubscriber(newComment));
  }

  calcPhotoSize() {
    window.setTimeout(() => {
      let element = this.photoContainer.nativeElement;
      let computedStyle = window.getComputedStyle(element);
      let elementHeight = element.clientHeight;  // height with padding
      let elementWidth = element.clientWidth;   // width with padding
      elementHeight -= parseFloat(computedStyle.paddingTop) + parseFloat(computedStyle.paddingBottom);
      elementWidth -= parseFloat(computedStyle.paddingLeft) + parseFloat(computedStyle.paddingRight);
      let maxWidth = elementWidth;
      let maxHeight = elementHeight;
      if (maxHeight > 10) {
        if (this.imageElement.nativeElement.clientWidth > 0 && this.maxWidth == maxWidth && this.maxHeight == maxHeight) {
          this.flipContainerWidth = parseFloat(this.imageElement.nativeElement.clientWidth);
        }
        else {
          this.calcPhotoSize();
        }
        this.maxHeight = maxHeight;
        this.maxWidth = maxWidth;
      }
      else {
        this.calcPhotoSize();
      }
    }, 200);
  }

  isEditable() {
    return this.photo.author && this.userName == this.photo.author.userName;
  }

  addedCommentSubscriber(newComment: CommentAdded) {
    if (newComment.ancestorOrSelf.photoId == this.photoId) {
      this.toasty.info({
        title: "Info",
        msg: "New comment added.",
        theme: "bootstrap",
        showClose: true,
        timeout: 10000
      });

      let index = this.photo.comments.findIndex((element, index, array) => {
        return (element.id == newComment.ancestorOrSelf.id);
      });
      if (index >= 0) // Add reply and expand ancestor
        this.photo.comments[index] = mergeNewComment(this.photo.comments[index], newComment.ancestorOrSelf);
      else // Add comment
        this.photo.comments.push(newComment.ancestorOrSelf);

      let commentId: number = newComment.id;
      window.setTimeout(() => {
        let comment: Comment = this.photo.comments.find(c => c.id == commentId);
        if (comment)
          comment.isNew = false;
        else {
          let reply: Comment;
          for (var i = 0; i < this.photo.comments.length; i++) {
            reply = findReplyInComment(commentId, this.photo.comments[i]);
            if (reply != null) {
              reply.isNew = false;
              break;
            }
          }
        }
      }, 30000);
    }
  }

  initializeMap() {
    if (this.hasMap === true && this.gmapElement != undefined) {
      let windowWidth = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;
      this.gmapHeight = (windowWidth > 575.98) ? 400 : 300;
      // Create map
      var mapProp = {
        center: new google.maps.LatLng(this.photo.centerLat, this.photo.centerLng),
        zoom: this.photo.mapZoom ? this.photo.mapZoom : 12,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      this.map = new google.maps.Map(this.gmapElement.nativeElement, mapProp);
      var marker = new google.maps.Marker({
        position: new google.maps.LatLng(this.photo.locLat, this.photo.locLng),
        map: this.map
      });
      this.map.panTo(marker.getPosition());
    }
  }

  resetNewComment() {
    this.newComment = {
      id: 0,
      photoId: this.photoId,
      parentId: null,
      content: "",
      author: {
        userName: "",
        firstName: "",
        lastName: "",
        displayName: "",
        createdDate: null,
        modifiedDate: null
      },
      connectionId: "",
      isNew: true,
      isReplying: false,
      isViewing: false,
      isEditing: false,
      areRepliesLoaded: false,
      numOfReplies: 0,
      replies: [],
      createdDate: null,
      modifiedDate: null
    };
  }

  submitComment() {
    var result$ = this.commentService.create(this.newComment);
    result$.subscribe(
      observable$ => {
        observable$.subscribe(
          comment => {
            this.toasty.success({
              title: "Success",
              msg: "Posted successfully.",
              theme: "bootstrap",
              showClose: true,
              timeout: 1500
            });
            this.photo.comments.push(comment);
            this.resetNewComment();
          });
      },
      err => {
        console.log(err);
      });
  }
}

<div id="view-photo">
  <div class="row">
    <div class="col-lg-6">
      <h3 class="header-container">
        <span class="header-text" title="{{ photo.name }}">{{ photo.name }}</span>
        <a class="btn btn-secondary header-button" href="/photo/edit/{{ photo.id }}" *ngIf="isEditable()"
          title="Edit Photo">
          <i class="fas fa-pencil-alt"></i>
        </a>
      </h3>
      <hr />
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6 photo-container" #photoContainer>
      <div class="flip-container mb-2" (click)="isShownBoundingBox = !isShownBoundingBox"
        [class.flip]="isShownBoundingBox" [style.width.px]="flipContainerWidth" [hidden]="maxWidth == 0">
        <div class="flipper">
          <div class="front">
            <!-- front content -->
            <img #imagePhoto src="{{ photo.filePath }}" class="img-thumbnail" [style.maxWidth.px]="maxWidth"
              [style.maxHeight.px]="maxHeight">
          </div>
          <div class="back">
            <!-- back content -->
            <img src="{{ photo.boundingBoxFilePath }}" class="img-thumbnail" [style.maxWidth.px]="maxWidth"
              [style.maxHeight.px]="maxHeight">
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="row" [class.mb-5]="!photo.album">
        <div class="col">
          <h4>Album</h4>
          <hr />
        </div>
      </div>
      <div class="row" *ngIf="photo.album">
        <div class="col">
          <a class="btn btn-outline-secondary mr-2 mb-2" [routerLink]="['/']"
            [queryParams]="{'albumId': photo.album.id}">{{photo.album.name}}</a>
        </div>
      </div>
      <div class="row" [class.mb-5]="!photo.photoCategories || photo.photoCategories.length == 0">
        <div class="col">
          <h4>Tags</h4>
          <hr />
        </div>
      </div>
      <div class="row" *ngIf="photo.photoCategories && photo.photoCategories.length > 0">
        <div class="col">
          <a *ngFor="let cat of photo.photoCategories" class="btn btn-outline-secondary mr-2 mb-2" [routerLink]="['/']"
            [queryParams]="{'catId': cat.id}">{{cat.name}}</a>
        </div>
      </div>
      <div class="row" [class.mb-5]="!hasMap">
        <div class="col">
          <h4>Location</h4>
          <hr />
        </div>
      </div>
      <div class="row">
        <div class="col">
          <div id="gmap-edit" #gmap [style.height.px]="gmapHeight"></div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6 mb-2">
      <div>
        <h4>New Comment</h4>
        <hr />
      </div>
      <div>
        <form id="newCommentForm" #f="ngForm" (ngSubmit)="f.form.valid && submitComment()" class="container pt-2">
          <div class="row">
            <div class="col-12">
              <label for="newComment" class="required">Comment:</label>
            </div>
            <div class="col-12">
              <div class="form-group">
                <textarea id="newComment" name="newComment" type="text" class="form-control"
                  [(ngModel)]="newComment.content" required></textarea>
              </div>
              <div class="form-group">
                <button class="btn btn-primary" type="submit" [disabled]="!f.valid">Post</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="row" *ngIf="photo.comments && photo.comments.length > 0">
    <div class="col-lg-6">
      <div>
        <h4>All Comments</h4>
        <hr />
      </div>
      <div>
        <app-reply-list [replies]="photo.comments" [userName]="userName"></app-reply-list>
      </div>
    </div>
  </div>
</div>

// src/WebSPA.React.Identity/ClientApp/src/components/ViewPhoto.tsx
import React, { Component } from 'react';
import { Row, Col } from 'reactstrap';
import { Photo } from '../models/photo';
import { User } from "../models/user";
import { SaveAlbum } from '../models/album';
import { PhotoService } from '../services/photo.service';
import './ViewPhoto.css';
//import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import GoogleMapReact from 'google-map-react';
import { RouteComponentProps } from 'react-router';
import { Link } from 'react-router-dom';
import { ReplyList } from './ReplyList';

interface IViewPhotoProps { }
interface IViewPhotoState {
    photo: Photo,
    isShownBoundingBox: boolean,
    hasMap: boolean | null,
    userName: string,
    flipContainerWidth: number,
    maxHeight: number,
    maxWidth: number,
    gmapHeight: number
}

interface IViewPhotoParams {
    id: string;
}

export class ViewPhoto extends Component<IViewPhotoProps & RouteComponentProps<IViewPhotoParams>, IViewPhotoState> {
    private photoService = new PhotoService();
    private photoId: number;
    private photoContainerRef: React.RefObject<HTMLDivElement>;
    private imageElementRef: React.RefObject<HTMLImageElement>;

    constructor(props: IViewPhotoProps & RouteComponentProps<IViewPhotoParams>) {
        super(props);
        let windowWidth = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;
        this.state = {
            photo: {
                id: 0,
                name: "",
                filePath: "",
                boundingBoxFilePath: "",
                width: 0,
                height: 0,
                photoCategories: [],
                locLat: -1,
                locLng: -1,
                centerLat: -1,
                centerLng: -1,
                mapZoom: -1,
                comments: [],
                totalComments: 0,
                createdDate: new Date(),
                modifiedDate: new Date(),
                author: new User(),
                album: new SaveAlbum()
            },
            isShownBoundingBox: false,
            hasMap: null,
            userName: "",
            flipContainerWidth: 0,
            maxHeight: 0,
            maxWidth: 0,
            gmapHeight: (windowWidth > 575.98) ? 400 : 300
        };
        this.googleApiLoadedHandler = this.googleApiLoadedHandler.bind(this);
        this.initializeMap = this.initializeMap.bind(this);
        this.handleResize = this.handleResize.bind(this);
        this.calcPhotoSize = this.calcPhotoSize.bind(this);
        this.photoId = parseInt(this.props.match.params.id);
        this.photoContainerRef = React.createRef();
        this.imageElementRef = React.createRef();
    }

    googleApiLoadedHandler(map: google.maps.Map) {
        window.setTimeout(() => {
            if (this.state.hasMap !== null) {
                this.initializeMap(map);
            }
            else {
                this.googleApiLoadedHandler(map);
            }
        }, 200);
    }

    handleResize(event: any) {
        this.calcPhotoSize();
    }

    calcPhotoSize() {
        window.setTimeout(() => {
            let element = this.photoContainerRef.current as HTMLDivElement;
            let computedStyle = window.getComputedStyle(element);
            let elementHeight = element.clientHeight;  // height with padding
            let elementWidth = element.clientWidth;   // width with padding
            elementHeight -= parseFloat(computedStyle.paddingTop) + parseFloat(computedStyle.paddingBottom);
            elementWidth -= parseFloat(computedStyle.paddingLeft) + parseFloat(computedStyle.paddingRight);
            let maxWidth = elementWidth;
            let maxHeight = elementHeight;
            if (maxHeight > 10) {
                if (this.imageElementRef.current?.clientWidth && this.imageElementRef.current?.clientWidth > 0 && this.state.maxWidth === maxWidth && this.state.maxHeight === maxHeight) {
                    this.setState({
                        flipContainerWidth: this.imageElementRef.current?.clientWidth
                    });
                }
                else {
                    this.calcPhotoSize();
                }
                this.setState({
                    maxHeight: maxHeight,
                    maxWidth: maxWidth
                });
            }
            else {
                this.calcPhotoSize();
            }
        }, 200);
    }

    initializeMap(map: google.maps.Map) {
        if (this.state.hasMap === true) {
            var marker = new google.maps.Marker({
                position: new google.maps.LatLng(this.state.photo.locLat, this.state.photo.locLng),
                map: map
            });
            map.panTo(marker.getPosition() as google.maps.LatLng);
        }
        else {
            this.setState({ gmapHeight: 0 });
        }
    }

    componentDidMount() {
        window.addEventListener("resize", this.handleResize);
        this.photoService.get(this.photoId).then(photo => {
            if (photo) {
                this.setState({
                    photo: photo,
                    hasMap: (photo.locLat != null) && (photo.locLng != null)
                });
                this.calcPhotoSize();
            }
            else {
                this.props.history.push('/');
            }
        });
    }
    componentWillUnmount() {
        window.removeEventListener("resize", this.handleResize);
    }

    render() {
        return (
            <div id="view-photo">
                <Row>
                    <Col lg={{ size: 6 }}>
                        <h3 className="header-container">
                            <span className="header-text" title={this.state.photo.name}>{this.state.photo.name}</span>
                            {/*
                                    <a className="btn btn-secondary header-button" href={"/photo/edit/" + this.state.photo.id } title="Edit Photo">
                                        <FontAwesomeIcon icon="pencil-alt" />
                                    </a>
                                */}
                        </h3>
                        <hr />
                    </Col>
                </Row>
                <Row>
                    <div className="col-lg-6 photo-container" ref={this.photoContainerRef}>
                        {this.state.maxWidth > 0 &&
                            <div className={"flip-container mb-2 " + (this.state.isShownBoundingBox ? 'flip' : '')}
                                onClick={(e) => { this.setState((s, p) => { return { isShownBoundingBox: !s.isShownBoundingBox }; }) }}
                                style={{ width: this.state.flipContainerWidth }}>
                                <div className="flipper">
                                    <div className="front">
                                        {/* front content */}
                                        <img alt={this.state.photo.name} src={this.state.photo.filePath} className="img-thumbnail" ref={this.imageElementRef}
                                            style={{ maxWidth: this.state.maxWidth, maxHeight: this.state.maxHeight }} />
                                    </div>
                                    <div className="back">
                                        {/* back content */}
                                        <img alt={this.state.photo.name} src={this.state.photo.boundingBoxFilePath} className="img-thumbnail"
                                            style={{ maxWidth: this.state.maxWidth, maxHeight: this.state.maxHeight }} />
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                    <Col lg={{ size: 6 }}>
                        <Row className={!this.state.photo.album ? "mb-5" : ""}>
                            <Col>
                                <h4>Album</h4>
                                <hr />
                            </Col>
                        </Row>
                        {this.state.photo.album &&
                            <Row>
                                <Col>
                                    {this.state.photo.album.name &&
                                        <Link className="btn btn-outline-secondary mr-2 mb-2" to={"/?albumId=" + this.state.photo.album.id}>{this.state.photo.album.name}</Link>
                                    }
                                </Col>
                            </Row>
                        }
                        <Row className={(!this.state.photo.photoCategories || this.state.photo.photoCategories.length === 0) ? "mb-5" : ""}>
                            <Col>
                                <h4>Tags</h4>
                                <hr />
                            </Col>
                        </Row>
                        {this.state.photo.photoCategories && this.state.photo.photoCategories.length > 0 &&
                            <Row>
                                <Col>
                                    {this.state.photo.photoCategories.map(photoCategories =>
                                        <Link key={photoCategories.id} className="btn btn-outline-secondary mr-2 mb-2" to={"/?catId=" + photoCategories.id}>{photoCategories.name}</Link>
                                    )}
                                </Col>
                            </Row>
                        }
                        <Row className={!this.state.hasMap ? "mb-5" : ""}>
                            <div className="col">
                                <h4>Location</h4>
                                <hr />
                            </div>
                        </Row>
                        <Row>
                            <Col>
                                <div id="gmap-edit" style={{ height: this.state.gmapHeight }}>
                                    <GoogleMapReact
                                        bootstrapURLKeys={{
                                            key: ""
                                        }}
                                        yesIWantToUseGoogleMapApiInternals
                                        defaultCenter={{ lat: 3.140853, lng: 101.693207 }} /* KUL */
                                        defaultZoom={12}
                                        onGoogleApiLoaded={({ map }) => this.googleApiLoadedHandler(map)}
                                        options={{ mapTypeId: 'roadmap' }}
                                    />
                                    {!this.state.hasMap &&
                                        <div id="gmap-edit-overlay" className="background-dark-lighter" style={{ top: 0, left: 0, width: "100%", height: "100%", zIndex: 1000, position: "absolute" }}>
                                        </div>
                                    }
                                </div>
                            </Col>
                        </Row>
                    </Col>
                </Row>
                {/*<Row>
                    <div className="col-lg-6 mb-2">
                        <div>
                            <h4>New Comment</h4>
                            <hr />
                        </div>
                        <div>
                            <form id="newCommentForm" className="container pt-2">
                                <div className="row">
                                    <div className="col-12">
                                        <label htmlFor="newComment" className="required">Comment:</label>
                                    </div>
                                    <div className="col-12">
                                        <div className="form-group">
                                            <textarea id="newComment" name="newComment" className="form-control" required></textarea>
                                        </div>
                                        <div className="form-group">
                                            <button className="btn btn-primary" type="submit">Post</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </Row>*/}
                {this.state.photo.comments && this.state.photo.comments.length > 0 &&
                    <Row>
                        <Col lg={{ size: 6 }}>
                            <div>
                                <h4>All Comments</h4>
                                <hr />
                            </div>
                            <div>
                                {<ReplyList replies={this.state.photo.comments} userName={this.state.userName}></ReplyList>}
                            </div>
                         </Col>
                    </Row>
                }
            </div>
        );
    }
}
