// MyAlbum.WebSPA/ClientApp/src/app/components/world-map/world-map.component.ts
import { PhotoService } from './../../services/photo.service';
import { Photo } from './../../models/photo';
import { Component, OnInit, QueryList, ViewChild, ViewChildren } from '@angular/core';
import MarkerClusterer from '@googlemaps/markerclustererplus';

declare var Tessarray: any;

@Component({
  selector: 'app-world-map',
  templateUrl: './world-map.component.html',
  styleUrls: ['./world-map.component.css']
})
export class WorldMapComponent implements OnInit {

  @ViewChild('gmap', { static: false }) gmapElement: any;
  map: google.maps.Map;
  @ViewChild('gmapSearchBox', { static: false }) gmapSearchBox: any;
  searchBox: google.maps.places.SearchBox;
  markers: google.maps.Marker[];
  markerCluster: MarkerClusterer;

  allPhotos: Photo[];
  viewportPhotos: Photo[];
  query: any = {};
  @ViewChildren('imageBoxes') imageBoxes: QueryList<any>;

  constructor(
    private photoService: PhotoService
  ) {
    this.initializeMap();
  }

  ngOnInit() {
  }

  ngAfterViewInit() {
    this.initializeMap();
    this.imageBoxes.changes.subscribe(t => {
      this.ngForRendered();
    });    
  }

  initializeMap() {
    if (this.gmapElement != undefined && this.gmapSearchBox != undefined) {
      // Get photos with location
      this.query.hasLocation = true;
      this.photoService.getAll(this.query)
        .subscribe(photos => {
          // Create map
          var mapProp = {
            center: new google.maps.LatLng(3.140853, 101.693207), // KUL
            zoom: 12,
            mapTypeId: google.maps.MapTypeId.ROADMAP
          };
          this.map = new google.maps.Map(this.gmapElement.nativeElement, mapProp);
          this.allPhotos = photos;
          if (this.allPhotos.length > 0) {
            var allBounds = new google.maps.LatLngBounds();
            this.markers = this.allPhotos.map((photo, i) => {
              var markerPosition = { lat: photo.locLat, lng: photo.locLng };
              var marker = new google.maps.Marker({
                position: markerPosition,
                label: "",
              });
              google.maps.event.addListener(marker, 'click', function () {
                this.map.setCenter(marker.getPosition());
                this.map.setZoom(this.map.getZoom() + 1);
              });
              google.maps.event.addListener(marker, 'rightclick', function () {
                this.map.setCenter(marker.getPosition());
                this.map.setZoom((this.map.getZoom() - 1) > 1 ? (this.map.getZoom() - 1) : 1);
              });
              allBounds.extend(markerPosition);
              return marker;
            });
            this.map.fitBounds(allBounds);
            this.markerCluster = new MarkerClusterer(this.map, this.markers, {
              imagePath: "/lib/@googlemaps/markerclustererplus/m"
            });
          }
          google.maps.event.addListener(this.map, 'bounds_changed', (e) => {
            var bound = this.map.getBounds();
            this.viewportPhotos = this.allPhotos.filter((photo) => {
              return bound.contains({ lat: photo.locLat, lng: photo.locLng });
            });
          });
          google.maps.event.addListener(this.map, 'click', (e) => {
            this.map.setCenter(e.latLng);
            this.map.setZoom(this.map.getZoom() + 2);
          });
          google.maps.event.addListener(this.map, 'rightclick', (e) => {
            this.map.setCenter(e.latLng);
            this.map.setZoom((this.map.getZoom() - 2) > 2 ? (this.map.getZoom() - 2) : 2);
          });
          // Create the search box and link it to the UI element.
          this.searchBox = new google.maps.places.SearchBox(this.gmapSearchBox.nativeElement);
          this.searchBox.addListener('places_changed', (e) => {
            var places = this.searchBox.getPlaces();
            if (places.length > 0) {
              var bounds = new google.maps.LatLngBounds();
              // For each place, get the icon, name and location.

              places.forEach(function (place) {
                if (!place.geometry) {
                  console.log("Returned place contains no geometry");
                  return;
                }

                if (place.geometry.viewport) {
                  // Only geocodes have viewport.
                  bounds.union(place.geometry.viewport);
                } else {
                  bounds.extend(place.geometry.location);
                }
              });

              this.map.fitBounds(bounds);

              this.viewportPhotos = this.allPhotos.filter((photo) => {
                return bounds.contains({ lat: photo.locLat, lng: photo.locLng });
              });
            }
          });
        });
    }
  }

  panTo(photo: Photo) {
    var location = new google.maps.LatLng({ lat: photo.locLat, lng: photo.locLng });
    this.map.setCenter(location);
  }

  ngForRendered() {
    var tessarray = new Tessarray(".explore-gallery", ".image-box", {
      selectorClass: false,
      boxTransition: false,
      boxTransformOutTransition: false,
      flickr: {
        // http://flickr.github.io/justified-layout/
        targetRowHeight: 150,
        targetRowHeightTolerance: 0.05,
        boxSpacing: {
          horizontal: 5,
          vertical: 5
        },
        containerPadding: 0
      }
    });
  }  
}

<div id="world-map">
  <div class="row">
    <div class="col-lg-4">
      <div class="explore-gallery">
        <div #imageBoxes class="image-box" *ngFor="let p of viewportPhotos" (click)="panTo(p)">
          <img src="{{ p.filePath }}" alt="{{ p.name }}">
          <a href="/photos/{{p.id}}" target="_blank" class="external-button"><i
              class="edit-link fas fa-external-link-alt"></i></a>
        </div>
      </div>
    </div>
    <div class="col-lg-8">
      <input id="gmapSearchBox" class="form-control mb-2" type="text" placeholder="Type location here..." #gmapSearchBox
        (keydown.enter)="$event.preventDefault()">
      <div id="gmap" #gmap></div>
    </div>
  </div>
</div>

// src/WebSPA.React.Identity/ClientApp/src/components/WorldMap.tsx
import React, { Component } from 'react';
import { Row, Col } from 'reactstrap';
import { Photo } from '../models/photo';
import { PhotoService } from '../services/photo.service';
import styles from './WorldMap.module.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import GoogleMapReact from 'google-map-react';
import MarkerClusterer from '@googlemaps/markerclustererplus';
import { GlobalDataContext } from '../context/GlobalDataContext';
import { DisplayMode } from '../models/globalData';

declare const Tessarray: any;

interface IWorldMapProps { }
interface IWorldMapState {
    viewportPhotos: Photo[]
}

export class WorldMap extends Component<IWorldMapProps, IWorldMapState> {
    static contextType = GlobalDataContext;
    context!: React.ContextType<typeof GlobalDataContext>;

    private photoService = new PhotoService();
    private allPhotos: Photo[] = [];
    private gmapSearchBoxRef: React.RefObject<HTMLInputElement>;

    constructor(props: IWorldMapProps) {
        super(props);
        this.state = {
            viewportPhotos: []
        };
        this.GoogleApiLoadedHandler = this.GoogleApiLoadedHandler.bind(this);
        this.gmapSearchBoxRef = React.createRef();
    }

    GoogleApiLoadedHandler(map: google.maps.Map) {
        this.photoService.getAll([]).then(data => {
            this.allPhotos = data;
            if (this.allPhotos.length > 0) {
                let allBounds = new google.maps.LatLngBounds();
                let markers = this.allPhotos.filter((photo) => photo.locLat && photo.locLng).map((photo, i) => {
                    let markerPosition = new google.maps.LatLng(photo.locLat, photo.locLng);
                    let marker = new google.maps.Marker({
                        position: markerPosition,
                        label: "",
                    });
                    google.maps.event.addListener(marker, 'click', () => {
                        map.setCenter(marker.getPosition() as google.maps.LatLng);
                        map.setZoom(map.getZoom() as number + 1);
                    });
                    google.maps.event.addListener(marker, 'rightclick', () => {
                        map.setCenter(marker.getPosition() as google.maps.LatLng);
                        map.setZoom((map.getZoom() as number - 1) > 1 ? (map.getZoom() as number - 1) : 1);
                    });
                    allBounds.extend(markerPosition);
                    return marker;
                });
                map.fitBounds(allBounds);
                let markerCluster = new MarkerClusterer(map, markers, {
                    imagePath: "/lib/@googlemaps/markerclustererplus/m"
                });
            }
            google.maps.event.addListener(map, 'bounds_changed', (e: any) => {
                let bound = map.getBounds();
                this.setState({
                    viewportPhotos: this.allPhotos.filter((photo) => {
                        return photo.locLat && photo.locLng && bound?.contains({ lat: photo.locLat, lng: photo.locLng });
                    })
                });
            });
            google.maps.event.addListener(map, 'click', (e: any) => {
                map.setCenter(e.latLng);
                map.setZoom(map.getZoom() as number + 2);
            });
            google.maps.event.addListener(map, 'rightclick', (e: any) => {
                map.setCenter(e.latLng);
                map.setZoom((map.getZoom() as number - 2) > 2 ? (map.getZoom() as number - 2) : 2);
            });
            // Create the search box and link it to the UI element.
            let searchBox = new google.maps.places.SearchBox(this.gmapSearchBoxRef.current as HTMLInputElement);
            searchBox.addListener('places_changed', (e: any) => {
                let places = searchBox.getPlaces();
                if (places && places.length > 0) {
                    let bounds = new google.maps.LatLngBounds();
                    // For each place, get the icon, name and location.

                    places.forEach(function (place) {
                        if (!place.geometry) {
                            console.log("Returned place contains no geometry");
                            return;
                        }

                        if (place.geometry.viewport) {
                            // Only geocodes have viewport.
                            bounds.union(place.geometry.viewport);
                        } else {
                            bounds.extend(place.geometry.location as google.maps.LatLng);
                        }
                    });

                    map.fitBounds(bounds);

                    this.setState({
                        viewportPhotos: this.allPhotos.filter((photo) => {
                            return bounds.contains({ lat: photo.locLat, lng: photo.locLng });
                        })
                    });
                }
            });
        });
    }

    render() {
        return (
            <div id="world-map">
                <Row>
                    <Col lg={{ size: 4, order: 1 }} className="order-2">
                        <div className={styles["explore-gallery"]}>
                            {this.state.viewportPhotos.map(photo =>
                                <div className="image-box rounded" key={photo.id}>
                                    <img src={photo.filePath} alt={photo.name} />
                                    <a href={"/photo/" + photo.id} target="_blank" className="external-button">
                                        <FontAwesomeIcon icon="external-link-alt" className="edit-link" />
                                    </a>
                                </div>
                            )}
                        </div>
                    </Col>
                    <Col lg={{ size: 8, order: 2 }} className="mb-lg-0 mb-2 order-1">
                        <input id="gmapSearchBox"
                            className="form-control mb-2"
                            type="text"
                            placeholder="Type location here..."
                            ref={this.gmapSearchBoxRef} />
                        <div id="gmap">
                            <GoogleMapReact 
                                bootstrapURLKeys={{
                                    key: "",
                                    libraries: 'places'
                                }}
                                yesIWantToUseGoogleMapApiInternals
                                onGoogleApiLoaded={({ map }) => this.GoogleApiLoadedHandler(map)}
                                defaultCenter={{ lat: 3.140853, lng: 101.693207 }} /* KUL */
                                defaultZoom={ 12 }
                                options={{ mapTypeId: 'roadmap' }}
                            />
                        </div>
                    </Col>
                </Row>
            </div>
        );
    }

    componentDidMount() {
        this.context?.setDisplayMode(DisplayMode.Photo);
    }

    componentDidUpdate(prevProps: IWorldMapProps, prevState: IWorldMapState) {
        const tessarray = new Tessarray("." + styles["explore-gallery"], ".image-box", {
            selectorClass: false,
            boxTransition: false,
            boxTransformOutTransition: false,
            flickr: {
                // http://flickr.github.io/justified-layout/
                targetRowHeight: 150,
                targetRowHeightTolerance: 0.25,
                boxSpacing: {
                    horizontal: 5,
                    vertical: 5
                },
                containerPadding: 0
            }
        });
    }
}
