// src/WebSPA.React.Identity/ClientApp/src/components/NavMenu.tsx
import React, { Component } from 'react';
import { Collapse, Container, Navbar, NavbarBrand, NavbarToggler, NavItem, NavLink } from 'reactstrap';
import { NavLink as RRNavLink } from 'react-router-dom';
import './NavMenu.css';
import '../toggle-switch.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { DisplayMode } from '../models/globalData';
import { GlobalDataContext } from '../context/GlobalDataContext';
import { RouteComponentProps, withRouter } from 'react-router';
import { LoginMenu } from './api-authorization/LoginMenu';

interface INavMenuProps {
}
interface INavMenuState {
    collapsed: boolean
}

class NavMenu extends Component<INavMenuProps & RouteComponentProps, INavMenuState> {
    static contextType = GlobalDataContext;
    context!: React.ContextType<typeof GlobalDataContext>;

    constructor(props: INavMenuProps & RouteComponentProps) {
        super(props);

        this.toggleNavbar = this.toggleNavbar.bind(this);
        this.changeDisplayMode = this.changeDisplayMode.bind(this);
        this.state = {
            collapsed: true
        };
    }

    toggleNavbar() {
        this.setState({
            collapsed: !this.state.collapsed
        });
    }

    changeDisplayMode(displayMode: DisplayMode) {
        let currentPath = window.location.pathname;

        switch (currentPath) {
            case "/":
                if (displayMode === DisplayMode.Album) {
                    this.props.history.push('/album');
                }
                else {
                    this.props.history.push('/');
                }
                break;
            case "/photo/new":
                if (displayMode === DisplayMode.Album) {
                    this.props.history.push('/album/new');
                }
                break;
            case "/album":
                if (displayMode === DisplayMode.Photo) {
                    this.props.history.push('/');
                }
                break;
            case "/album/new":
                if (displayMode === DisplayMode.Photo) {
                    this.props.history.push('/photo/new');
                }
                break;
        }

        console.log("currentPath = " + currentPath);
        console.log("displayMode = " + displayMode);
    }

    render() {
        return (
            <header>
                <Navbar className="navbar navbar-expand-md navbar-toggleable-md navbar-dark box-shadow-bottom background-dark-darker" light>
                    <Container fluid={true}>
                        <NavbarBrand tag={RRNavLink} to="/" className="navbar-brand text-light">
                            <img className="rounded" src="/logo.jpg" alt="logo.jpg" height="40px" width="40px" />
                            <span> My Album</span>
                        </NavbarBrand>
                        <div className="d-inline-flex">
                            <div className="rounded switch-toggle alert display-mode mobile">
                                {!this.context?.globalData.enableDisplayMode && <div className="overlay"></div>}
                                <div>
                                    <input id="photo_mobile" name="displayMode_mobile" type="radio" value="photo"
                                        checked={this.context?.globalData.displayMode === DisplayMode.Photo}
                                        disabled={!this.context?.globalData.enableDisplayMode}
                                        onChange={(e) => this.changeDisplayMode(DisplayMode.Photo)} />
                                    <label htmlFor="photo_mobile">Photo</label>
                                    <input id="album_mobile" name="displayMode_mobile" type="radio" value="album" 
                                        checked={this.context?.globalData.displayMode === DisplayMode.Album}
                                        disabled={!this.context?.globalData.enableDisplayMode}
                                        onChange={(e) => this.changeDisplayMode(DisplayMode.Album)} />
                                    <label htmlFor="album_mobile">Album</label>
                                    <a className="btn btn-primary"></a>
                                </div>
                            </div>
                            <span className="separator mobile"></span>
                            <NavbarToggler onClick={this.toggleNavbar} className="mr-2 text-light" />
                        </div>
                        <Collapse className="d-md-inline-flex flex-md-row-reverse" isOpen={!this.state.collapsed} navbar>
                            <ul className="navbar-nav flex-grow">
                                <NavItem>
                                    {this.context?.globalData.displayMode === DisplayMode.Photo &&
                                        <NavLink tag={RRNavLink} className="text-light" to="/" activeClassName="link-active" exact>
                                            <FontAwesomeIcon icon="torii-gate" /> Explore
                                        </NavLink>
                                    }
                                    {this.context?.globalData.displayMode === DisplayMode.Album &&
                                        <NavLink tag={RRNavLink} className="text-light" to="/album" activeClassName="link-active" exact>
                                            <FontAwesomeIcon icon="torii-gate" /> Explore
                                        </NavLink>
                                    }
                                </NavItem>
                                {this.context?.globalData.displayMode === DisplayMode.Photo &&
                                    <NavItem>
                                        <NavLink tag={RRNavLink} className="text-light" to="/worldmap" activeClassName="link-active">
                                            <FontAwesomeIcon icon="globe" /> World Map
                                        </NavLink>
                                    </NavItem>
                                }
                                {this.context?.globalData.displayMode === DisplayMode.Album &&
                                    <NavItem className="disabled">
                                        <span className="nav-link text-dark">
                                            <FontAwesomeIcon icon="globe" /> World Map
                                        </span>
                                    </NavItem>
                                }
                                <NavItem>
                                    {this.context?.globalData.displayMode === DisplayMode.Photo &&
                                        <NavLink tag={RRNavLink} className="text-light" to="/photo/new" activeClassName="link-active">
                                            <FontAwesomeIcon icon="plus" /> Add
                                        </NavLink>
                                    }
                                    {this.context?.globalData.displayMode === DisplayMode.Album &&
                                        <NavLink tag={RRNavLink} className="text-light" to="/album/new" activeClassName="link-active">
                                            <FontAwesomeIcon icon="plus" /> Add
                                        </NavLink>
                                    }
                                </NavItem>
                                <LoginMenu/>
                            </ul>
                            <span className="separator"></span>
                            <div className="rounded switch-toggle alert display-mode">
                                {!this.context?.globalData.enableDisplayMode && <div className="overlay"></div>}
                                <div>
                                    <input id="photo" name="displayMode" type="radio" value="photo"
                                        checked={this.context?.globalData.displayMode === DisplayMode.Photo}
                                        disabled={!this.context?.globalData.enableDisplayMode}
                                        onChange={(e) => this.changeDisplayMode(DisplayMode.Photo)} />
                                    <label htmlFor="photo">Photo</label>
                                    <input id="album" name="displayMode" type="radio" value="album"
                                        checked={this.context?.globalData.displayMode === DisplayMode.Album}
                                        disabled={!this.context?.globalData.enableDisplayMode}
                                        onChange={(e) => this.changeDisplayMode(DisplayMode.Album)} />
                                    <label htmlFor="album">Album</label>
                                    <a className="btn btn-primary"></a>
                                </div>
                            </div>
                        </Collapse>
                    </Container>
                </Navbar>
            </header>
        );
    }
}

export default withRouter(NavMenu);

// MyAlbum.WebSPA/ClientApp/src/app/components/nav-menu/nav-menu.component.ts
import { DisplayMode, GlobalData } from './../../models/globalData';
import { Component } from '@angular/core';
import { GlobalDataService } from 'src/app/services/globalData.service';
import { Location } from '@angular/common';
import { Router, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-nav-menu',
  templateUrl: './nav-menu.component.html',
  styleUrls: ['./nav-menu.component.css']
})
export class NavMenuComponent {
  isExpanded = false;
  globalData: GlobalData;
  displayMode: DisplayMode;

  constructor(
    private globalDataService: GlobalDataService,
    private location: Location,
    private router: Router,
    private route: ActivatedRoute
  ) {
    this.globalDataService.currentGlobalData$.subscribe(globalData => {
      this.globalData = globalData;
      this.displayMode = this.globalData.displayMode;
    });
    this.route.queryParams.subscribe(params => {
      if (params['displayMode']) {
        this.changeDisplayMode(params['displayMode']);
      }
      else if (this.location.path().indexOf(DisplayMode.Album) >= 0) {
        this.changeDisplayMode(DisplayMode.Album);
      }
      else {
        this.changeDisplayMode(DisplayMode.Photo);
      }
    });
  }

  collapse() {
    this.isExpanded = false;
  }

  toggle() {
    this.isExpanded = !this.isExpanded;
  }

  changeDisplayMode(displayMode: string) {
    let currentPath = this.location.path();

    if (currentPath == "/worldmap") {
      this.displayMode = DisplayMode.Photo;
    }
    else {
      this.globalData.displayMode = displayMode as DisplayMode;
      this.globalDataService.changeDisplayMode(this.globalData);
      this.displayMode = displayMode as DisplayMode;

      switch (currentPath) {
        case "":
        case "?displayMode=album":
        case "?displayMode=photo":
          if (displayMode == DisplayMode.Album) {
            this.router.navigate(["album/"]);
          }
          else {
            this.router.navigate(["/"]);
          }  
          break;
        case "/photo/new":
          if (displayMode == DisplayMode.Album) {
            this.router.navigate(["album/new"]);
          }
          break;
        case "/album":
          if (displayMode == DisplayMode.Photo) {
            this.router.navigate(["/"]);
          }
          break;
        case "/album/new":
          if (displayMode == DisplayMode.Photo) {
            this.router.navigate(["photo/new"]);
          }
          break;
      }
    }

    console.log("currentPath = " + currentPath);
    console.log("displayMode = " + this.displayMode);
  }
}

<header>
  <nav
    class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"
  >
    <div class="container-fluid">
      <a class="navbar-brand" [routerLink]="['/']">My Album</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target=".navbar-collapse"
        aria-label="Toggle navigation"
        [attr.aria-expanded]="isExpanded"
        (click)="toggle()"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div
        class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse"
        [ngClass]="{ show: isExpanded }"
      >
        <ul class="navbar-nav flex-grow">
          <li
            class="nav-item"
            [routerLinkActive]="['link-active']"
            [routerLinkActiveOptions]="{ exact: true }"
          >
            <a class="nav-link text-dark" [routerLink]="['/']">
              <i class="fas fa-home"></i> Home
            </a>
          </li>
          <li class="nav-item" [routerLinkActive]="['link-active']">
            <a class="nav-link text-dark" [routerLink]="['/photos/new']">
              <i class="fas fa-plus"></i> Add Photo
            </a>
          </li>
          <!-- <li class="nav-item" [routerLinkActive]="['link-active']">
            <a class="nav-link text-dark" [routerLink]="['/counter']">Counter</a>
          </li>
          <li class="nav-item" [routerLinkActive]="['link-active']">
            <a class="nav-link text-dark" [routerLink]="['/fetch-data']">Fetch data</a>
          </li> -->
        </ul>
      </div>
    </div>
  </nav>
</header>
